version: 2
updates:
  - package-ecosystem: 'npm' # See documentation for possible values
    directory: '/' # Location of package manifests
    open-pull-requests-limit: 30
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '08:00'
      timezone: 'Asia/Tokyo'
    ignore:
      - dependency-name: '@types/node'
        versions: '>=20'
