# Directory pattern
infra:
  - changed-files:
      - any-glob-to-any-file: '**/*.ts'

github_actions:
  - changed-files:
      - any-glob-to-any-file: '.github/**'

documentation:
  - changed-files:
      - any-glob-to-any-file: 'docs/**'
      - any-glob-to-any-file: '**/*.md'

tests:
  - changed-files:
      - any-glob-to-any-file: 'test/**'

# Branch pattern
feature:
  - head-branch: ['^feature/', '^feat']
fix:
  - head-branch: ['^fix/']

