pull_request_rules:
  - name: automatic merge of Dependabot PRs
    actions:
      queue:
        name: default
        method: squash
        commit_message_template: |-
          {{ title }} (#{{ number }})
          {{ body }}
    conditions:
      - -title~=(WIP|wip)
      - -label~=(blocked|do-not-merge)
      - -merged
      - -closed
      - author=dependabot[bot]
      - status-success=build-actions workflow
