########################################################################
#  Node.jsのセットアップとパッケージインストール
########################################################################

name: "setup node and insrtall packages"
runs:
  using: "composite"
  steps:
    - name: Use Node.js 20.17.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.17.x

    - name: Cache dependencies
      id: node_modules_cache_id
      uses: actions/cache@v4
      with:
        path: '**/node_modules'
        key: node-modules-${{ hashFiles('**/package-lock.json') }}

    - name: Setup dependencies
      if: ${{ steps.node_modules_cache_id.outputs.cache-hit != 'true' }}
      run: npm ci
      shell: bash
