name: build-actions
run-name: ${{ github.actor }} is running ${{ github.workflow }} workflow
on:
  pull_request:
  workflow_dispatch:
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: build
        uses: ./.github/workflows/build
