name: build-actions
run-name: ${{ github.workflow }} workflow
on:
  pull_request:
  workflow_dispatch:
jobs:
  build-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Set AWS Account Information
        run: |
          echo "DEV_ACCOUNT_ID=${{ secrets.DEV_ACCOUNT_ID }}" >> $GITHUB_ENV
          echo "PROD_ACCOUNT_ID=${{ secrets.PROD_ACCOUNT_ID }}" >> $GITHUB_ENV

      - uses: actions/checkout@v4

      - name: build
        uses: ./.github/workflows/build
