name: cdk-deploy-actions
run-name: ${{ github.workflow }} workflow
on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      AWS_ACCOUNT_NAME: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}
    steps:
      - name: Set AWS Account Information
        run: |
          if [[ ${{ github.ref }} == 'refs/heads/dev' ]]; then
            echo "ROLE_TO_ASSUME=arn:aws:iam::${{ secrets.DEV_ACCOUNT_ID }}:role/ghac-cdk-deploy-role" >> $GITHUB_ENV
          elif [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
            echo "ROLE_TO_ASSUME=arn:aws:iam::${{ secrets.PROD_ACCOUNT_ID }}:role/ghac-cdk-deploy-role" >> $GITHUB_ENV
          fi
          echo "DEV_ACCOUNT_ID=${{ secrets.DEV_ACCOUNT_ID }}" >> $GITHUB_ENV
          echo "PROD_ACCOUNT_ID=${{ secrets.PROD_ACCOUNT_ID }}" >> $GITHUB_ENV

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}
          aws-region: ap-northeast-1

      - uses: actions/checkout@v4

      - name: build
        uses: ./.github/workflows/build

      - name: CDK Diff Check
        run: npx cdk diff "$AWS_ACCOUNT_NAME/*"

      - name: CDK Deploy
        run: npx cdk deploy "$AWS_ACCOUNT_NAME/*"
