name: cdk-github-actions
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::533267250677:role/ghac-cdk-deploy-role
          aws-region: ap-northeast-1

      - uses: actions/checkout@v4

      - name: Use Node.js 18.19.0
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      
      - name: Setup dependencies
        run: npm ci

      - name: Build
        run: npm run build

      # - name: Unit tests
      #   if: contains(github.event_name, 'pull_request')
      #   run: npm run test:app

      # - name: CDK Diff Check
      #   if: contains(github.event_name, 'pull_request')
      #   run: npm run cdk:diff
      #   env:
      #     AWS_DEFAULT_REGION: 'ap-northeast-1'
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Snapshot tests
        # if: contains(github.event_name, 'pull_request')
        run: npm run test -- -u

      - name: CDK Deploy
        # if: contains(github.event_name, 'push')
        run: npx cdk deploy "dev/*"
      #   env:
      #     AWS_DEFAULT_REGION: 'ap-northeast-1'
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

