name: cdk-github-actions
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::533267250677:role/ghac-cdk-deploy-role
          aws-region: ap-northeast-1

      - uses: actions/checkout@v4

      - name: Use Node.js 18.19.0
        uses: actions/setup-node@v4
        with:
          node-version: 18
      
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      
      - name: Setup dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: CDK Diff Check
        run: npx cdk diff

      - name: FineGrained Assertions tests
        run: npm run test:fga

      - name: CDK Deploy
        # if: contains(github.event_name, 'push')
        run: npx cdk deploy "dev/*"
