name: 'cdk-pull-request-actions'
run-name: ${{ github.actor }} is running workflow
on:
  pull_request:
    branches:
      - main
jobs:
  cdk-diff:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::533267250677:role/ghac-cdk-deploy-role
          aws-region: ap-northeast-1

      - uses: actions/checkout@v4

      - name: Use Node.js 18.19.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.19.x

      - name: Setup dependencies
        if: ${{ steps.node_modules_cache_id.outputs.cache-hit != 'true' }}
        run: npm ci

      - uses: tsuba3/cdk_plan_action@main
        with:
          aws-region: 'ap-northeast-1'
