name: 'cdk-pull-request-actions'
run-name: ${{ github.actor }} is running workflow
on:
  pull_request:
    branches:
      - main
jobs:
  cdk-diff:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 18.19.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.19.x

      - name: Setup dependencies
        if: ${{ steps.node_modules_cache_id.outputs.cache-hit != 'true' }}
        run: npm ci

      - uses: tsuba3/cdk_plan_action@main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          aws-region: 'ap-northeast-1'
