name: 'cdk-pull-request-actions'
run-name: ${{ github.actor }} is running workflow
on:
  pull_request:
    branches:
      - main
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: tsuba3/cdk_plan_action@main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          aws-region: 'ap-northeast-1'
