########################################################################
# mainブランチに対するプルリクエストを作成する
########################################################################

name: main-create-pull-request-action
run-name: ${{ github.workflow }} workflow
on:
  push:
    branches:
      - 'build**'
      - 'chore**'
      - 'ci**'
      - 'docs**'
      - 'feat**'
      - 'fix**'
      - 'perf**'
      - 'refactor**'
      - 'revert**'
      - 'style**'
      - 'test**'
# 全パーミッションの無効化
permissions: {}
# デフォルトシェルでパイプエラーを有効化
defaults:
  run:
    shell: bash
# ワークフローが複数起動したら自動キャンセル
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  main-create-pull-request:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment:
      name: dev
    permissions:
      contents: write
      pull-requests: write
    steps:
      # Bashトレーシングオプション
      - run: set -x

      # 前提情報の出力
      - run: cat $GITHUB_EVENT_PATH
      - run: lsb_release -d
      - run: gh --version

      - uses: actions/checkout@v4

      - name: create pull request
        uses: ./.github/workflows/create-pull-request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: "main"
          TITLE: "pre-release_from_${{ github.ref_name }}"
