########################################################################
# pull requestにラベルを付与
########################################################################

name: pull-request-labeler-action
run-name: ${{ github.workflow }} workflow
on:
  pull_request:
# 全パーミッションの無効化
permissions: {}
# デフォルトシェルでパイプエラーを有効化
defaults:
  run:
    shell: bash
# ワークフローが複数起動したら自動キャンセル
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  label:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      pull-requests: write
    steps:
      # Bashトレーシングオプション
      - run: set -x

      # 前提情報の出力
      - run: cat $GITHUB_EVENT_PATH
      - run: lsb_release -d
      - run: gh --version

      - uses: actions/labeler@v5
        with:
          configuration-path: .github/configs/labeler.yml
